### ISSUE TITLE
Cannot play sound on window.onload

### ISSUE THREAD

**Issue by esoadamo** [QRGameStudio/web-qgo.eu#11]
**Expected behavior**
When I start the game, the music stars playing and all other sounds work, as on [qrpr](http://qrpr.eu/html.html#XQAAAAIOBgAAAAAAAAA/FIIn7FHykSRmQ6BAqMo9fBG6BsAE78az3nAv4lu4SD9Lbxh/SXqDzgPUzDoB0C/CXzJxrxuCaWuPJX8Qa2l+9KVIgm1QvvrqDLho9a49FIQUd1Vjzp7t+V02xBeGuzEGcizjnYMStLjLO/W0W271ntB+z7SSUB3OzOjDcdCFaQW/x+W2ZmDdlH1qgzfYhqg7ZeZ7qSQWxsTwyHgo9aYfJkWWXp+GFdzYsPc2xhPd2qUvHX7RBYQ4W5DrW+ogeeuohIFarSHRo1lauc5XJPcJBVqxwHAcDH0a1AIHSjQKXVOJTK8dbHvOLK+j6+q/LIymAl9WVQjdRWhXOeu7zIqrH5DdfwGww/4EZGA1Ca9KGM069PLBweOP1GBoJkUdWH1gSkS6ztS41sFNTCa/XRVg010Dn2nRDgrD7TicJg2BHW6WZUVAAHm5qz3r1IkaZsnV3hpCNpXVQ4MgjcjJLkTKYEAW8dQlu1hJD8v06WgWzJ++OTNnAlYVbzdFSvqKmbDqIRHp1K+qj2RNoIZ4yb76Jc7Rgnpv0parSd3qtYxfa9/Z/eIkQc1bt0R1Tb7a3oDamPHMgmDYoquqzhn18xzWmdsuQQ8q7zuoOIzK2j6ZhSs72jNCmgI7e7izANr6ecmGm8USUfaya7kI+1k+JwmFYMJ9P0Mkcp6573TSvlWvyrhnYYRkvGa44odX/Slow+PrvYAAcPqk6+/2DzxZaAVVJIsnTdocjdzkG7g1OTIXLkZLitEgCwUYhia3Dy0XpBRfRkSXgRsMiMXYvwCe3/v5DRwK+X/1GYS9SmO1x5KV+fbm05zxRCoipHK6RwnXHYA0/kHHytwdbI4lW3Wdt32LKzdwujO5Vt0ast8O0AVE42JJegKX6rs052nRBOAD0xn0FVQ7+4ZBmtJAxFS128c00NhlDyZ1mJtaDGfXmcZ5oBAmx8xlj7YBGcjJ7LjWTR3ZBoGtbEFMXFKRV5GMLrs2Vyv8q/wW6N2UNdpQA7uYmNrdBDXZ+ln5vooUiuL1anI3WADzaxyIDMxOilBjtZ1jukexQAL4KJ0Wh90UVtMxcaYHzMLXj9g9NSOlCKb+0oeU0+xQma5adA4q/eegzrZg7vX+ozUYjChxt1bRug/esAINNw1Hsittpunx7Cya+MokgORtUQn0x+UdJKVfUP712boqyVKf2XKRyVd/VdWmBhB9jm30U0lUgTK+3cV0UXU6iJpX4Ifvkc1pDC3hK2Kv5OrQVRnMfGTFDdKREs+uqC/8EG7HdcYbAr7hALOfTZnLHa0pWXPgR2DvN/gknZnZUDqXgi//ew9AAA==)

**Current behavior**
When I try to play a game which stars a sound immediately after `window.onload` is called, the following error appers:
```
Uncaught ReferenceError: GStorage is not defined
    GVolume https://qgo.eu/lib/js/GSound.js:25
    create https://qgo.eu/lib/js/GSound.js:76
    GTone https://qgo.eu/lib/js/GSound.js:81
    <anonymous> https://qgo.eu/lib/js/GSound.js:341
GSound.js:25:21
    GVolume https://qgo.eu/lib/js/GSound.js:25
    create https://qgo.eu/lib/js/GSound.js:76
    GTone https://qgo.eu/lib/js/GSound.js:81
    <anonymous> https://qgo.eu/lib/js/GSound.js:341
```

**Steps to reproduce**
[Can be tested on this game](https://qgo.eu/Game/CBBM0000021R3000000000001Z2J12FV2HYA8J8TJ3M10AHJHXFG8VM1P00KQWDCYYE0QY4PXR90ZMPVRRFX4QN0YE0FACREG1U0QW4QTJE6QHQ0K9DE7JAZRGDDMQXX559216UM5YZBN0TE38YPQ3U5442HVNARYEKVPZJQ9PRGBRDETH0TT2TRWXGC9B9E6B7FUV8PVEYPFD0ZPFPJ9507EETKMC6WEGGNMGBFY7WPV6CR6XJHYPN0TQV23AGEV5WTXUJ90PRV2F1J3R53UUC7T68PB5X7W62QEDHC7Q6V317QEUMMQHUZPH0P23GPWGXDDYM83TXEM890AUNMGX38UTBAWWWNT4YW4GAPNHR1R1R33X3BA041UA6G55UMW99JQHUV3VTRPAZ8ZBXAZJT35609FNCN88VN2PGNTTXEXWT2NB3Y8DUZR1P31ZW134C0UGKBUA336KNX7JR70Y73YMC1M2CH8XB1YP0JJ4QB7D9E6PR56MR9NZBMAP1MUX0EFPKM8E1B1YUE4W4R6R27BEJTJMAG00F6WUPFFBUJ4HMTP9UQF1MGHPJQAM70T0HQ4CJBJ4T9G405QHUGJVPP291Z5Z9UB82V69ZFHT6DKG4NGNDWVMAJQUHACV1UH127MX9BXAHXJ4V846F34VXYH5TV8R4YKFUABAPJEXXAURRQVBVZCZVRH4876NQDU4EN6VXPPYG3D9HWECG9GDH8NBNB71KXFK3KB9KPTE847JNVTVN0W8TJPU7UCRAATVV8TM56G27DXVHCR0VBX7KJC6KF2H4MFPP9NVJ27VB4Z2E2C5C317UFU34HT9XEFFEK9BWNDFTAW6ERC4CJY6DE72GXBZUAB8RFHYQFC001RFN97BXZV0YF2TD02NA94B4X6XM74DVKJ1QE1N74T1EBJ69E5D280B0MC8C9NQ1WPHF90MBX3495W13C68HHERQW09XQZVZ46HR2QTFZUHK15X99HVBHWJJQWZDTPKKKRM8AH2MHTBMHR9UWER0D7Y873WNQ0XDJ72APVNKPVQV2TB6XRBMCXTAVEHNCPZ1V80AH73C94QM0MQXAXK9TV9U42E00YK37U1AN1VZE3436PJ83259DEVRWUD1P351WK7B64VB866FNWTRTWU0416RZ66B3XP04CWHJFCQ3B4U7ET0U0UUV219HE554AQJ662XETPAWNZTAZW2VMDV51NV9807EWRK3DDU11NV7X5KYDYH8A8NRQND9T3EP00YDNHT20CTH78MM33PPEP7EJ7P5005Y18KMB8FQ8MAV9K2WD60Z6C5NWFV0YKA8X512KFXMM7JK9YRM4TNTD783HAZQKU1KNPC3QFBZN36MC8RA3HPXBD3EGFVUR0439Q1N3V4AVDMVMZ3V1CKBWCM940WHPN22FMRZJHU955BX8FXXETQ8NCJMMZV5T93JAQFXAXB9G621YRWVFMAD4N909JQVEWAX2HEMX8H6JQW23YZ4EDD462VR9BCAQY9UPGAMCWRZ34RM6X548JTYQAGBZW21QCEXE63C1BXR80PEFMV6EB3PPJJPBKW13P1VTQZ0J9V6ETA0X9F0HFZXXGYG00)

**Possible cause**
`GStorage` is not loaded before `GSound`, but `GSound` depends on `GStorage`

**Comment by StastnyJ** [comment]
The order of loading external libraries depends on the order of the elements in this array.

![Screenshot_20210223-202258.jpg](https://user-images.githubusercontent.com/10522096/108896346-15f99100-7615-11eb-96cb-8f02b1d7c66f.jpg)

Before I fix this, do you see any other dependency, which is not fulfilled?

**Comment by esoadamo** [comment]
In qrpr ([here](https://github.com/QRGameStudio/web-qrpr.eu/blob/c157db7c753dfadadcead5b4f293aa54a7f50f59/lib/_GGamesStorage.js#L43)) the order is following:
- jquery
- bootstrap
- renderer
- peerjs
- gmodal
- gpopup
- gsound
- gtheme
- gmultiplayer
- ggamedata
- gut

Can you please make it the same? That should fix it.

**Comment by StastnyJ** [comment]
Where is GStorage? I inserted it between peerjs and GModal, is it ok?

**Comment by esoadamo** [comment]
Welp, this is weird, GStorage is not inside the injection code, but still works :shrug:
Yes, that location should be perfect
