### ISSUE TITLE
Volume control for GMusic

### ISSUE THREAD

**Issue by esoadamo** [QRGameStudio/web-qgo.eu#2]
In qrpr there is a volume control called GVolume, would be nice if the app could use the same feature,

Properties:
.volume: int <0-100>
.muted: bool
Functions:
mute(bool)
show(bool) - shows the GUI control
setVolume(int <0-100>

https://github.com/QRGameStudio/web-qrpr.eu/blob/master/lib/musicComposer.js

**Comment by StastnyJ** [comment]
Already included.
