### ISSUE TITLE
Pass games after #

### ISSUE THREAD

**Issue by esoadamo** [QRGameStudio/web-qgo.eu#5]
Please, change the way that the games are received from `/Game/<b32>` to `/Game/#<b32>`. The part after the hash can be read for example as it is implemented in [web-qrpr](https://github.com/QRGameStudio/web-qrpr.eu/blob/70797c1914ca8d0c78f8929bf6ce8f9428174e31/html.js#L38).

**Comment by StastnyJ** [comment]
Now the qgo.eu application supports both types of links,  `/Game/<b32>` as well as  `/Game/#<b32>`
