### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by StastnyJ** [QRGameStudio/web-qgo.eu#6]

**Comment by esoadamo** [comment]
Relevant passages from qrpr:
- https://github.com/QRGameStudio/web-qrpr.eu/blob/70797c1914ca8d0c78f8929bf6ce8f9428174e31/lib/gamesStorage.js#L180
- https://github.com/QRGameStudio/web-qrpr.eu/blob/70797c1914ca8d0c78f8929bf6ce8f9428174e31/lib/gamesStorage.js#L198

**Comment by StastnyJ** [comment]
Done
